spring:
    datasource:
        url: projectwoon.cnlle4ggkcrb.ap-northeast-2.rds.amazonaws.com
        driverClassName: org.mariadb.jdbc.Driver
        username: projectwoon1
        password: projectwoon1
    jpa:
        database-platform: database-platform:org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: update 
server:
    port: 9000
